author="friendfeed"
title="friendfeed"
base_url = "https://friends0ft.github.io/friendfeed"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = [ "atom.xml", "rss.xml", "calendar.ics" ]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
TZ = "America/Denver" # Also hardcoded in scripts/lib.py
